In [2]:

import numpy as np
a = np.array([2, 3, 4])
b = np.array([3, 4, 5])
print(a * b)


[ 6 12 20]


In [6]:
import numpy as np
l= np.array([[1,2,3],[4,5,6],[4,4,5]])
t= np.array([[1,3,2],[4,7,6],[4,3,5]])
print(l.ndim)
summation=l*t
print(summation)
print(summation.ndim)

2
[[ 1  6  6]
 [16 35 36]
 [16 12 25]]
2


In [10]:
import numpy as np;
genteraArray = np.arange(1,11)
generateZero = np.ones((4,6))
print(genteraArray)
print(generateZero)

[ 1  2  3  4  5  6  7  8  9 10]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [1]:
import numpy as np;
arr= np.linspace(1,9,5)
print(arr)

[1. 3. 5. 7. 9.]


In [2]:
import numpy as np;
np.random.randint(10,20,15)
np.random.randint(20,50,10)


array([36, 43, 39, 45, 47, 36, 43, 38, 37, 42], dtype=int32)

In [5]:
# array attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],    # Layer 1 (2D matrix)
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]  # Layer 2 (2D matrix)
])
print(arr_3d .ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


In [31]:
arr.shape


(3, 3)

In [30]:
arr.size

9

In [32]:
arr.dtype

dtype('int64')

In [34]:
# array methods
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.min()

np.int64(1)

In [36]:
arr.max()

np.int64(9)

In [37]:
arr.sum()

np.int64(45)

In [45]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [46]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [47]:
arr.std()

np.float64(2.581988897471611)

In [48]:
arr.argmax()

np.int64(8)

In [49]:
arr.argmin()

np.int64(0)

In [50]:
# reshape and resize
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])