In [ ]:
import numpy as np;
# Array operations

In [1]:
# arithmetic operations
import numpy as np;
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1


array([12,  9, 19, 17, 15, 18, 17, 17,  8,  5,  6, 14,  5, 14, 14,  5, 17,
       11, 14, 18], dtype=int32)

In [8]:
print(a1**a2)

[      1     128    6561  262144 9765625]


In [10]:
# broadcasting
l = [10,20,30,40]
arr =np.array(l)
arr+10

array([20, 30, 40, 50])

In [11]:

arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [13]:
# deep and shallow copy
a = np.arange(1,21)
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# if you slice array then it save in other location but when you assign one variable to other than it refrence to one another


In [19]:
# matrix operations
A=np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A

array([[1, 2],
       [3, 4]])

In [20]:
A@B

array([[19, 22],
       [43, 50]])

In [21]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [24]:
A
B

array([[5, 6],
       [7, 8]])

In [27]:
# advance array manipulation
# stacking array
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
np.hstack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [29]:
np.column_stack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [30]:
# splitting array
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [35]:
a= np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [39]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
