In [2]:
import numpy as np;
sudoku = np.array([[5,3,4,6,7,8,9,1,2],
                   [6,7,2,1,9,5,3,4,8],
                   [1,9,8,3,4,2,5,6,7],
                   
                   [8,5,9,7,6,1,4,2,3],
                   [4,2,6,8,5,3,7,9,1],
                   [7,1,3,9,2,4,8,5,6],

                   [9,6,1,5,3,7,2,8,4],
                   [2,8,7,4,1,9,6,3,5],
                   [3,4,5,2,8,6,1,7,9]
                  ])
sudoku


array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [3]:
b=np.sum(sudoku,axis=0)
for i in b:
    if i !=45:
        print("suduku is not valid")
        break
    else:
        print("for rows it is valid")


for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid


In [4]:
c=np.sum(sudoku,axis=1)
for i in c:
    if i !=45:
        print("sudoku is not valid")
        break
    else:
        print("for columns it is valid")

for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid


In [5]:
slice = sudoku[0:3,0:3]
print(slice)
np.sum(slice,axis=0)

[[5 3 4]
 [6 7 2]
 [1 9 8]]


array([12, 19, 14])

In [6]:
# slicing all the arrays at once using loops
for i in range(0,9,3):
    for j in range(0,9,3):
        n=sudoku[i:i+3,j:j+3]
        print(n)
        print(n.sum())
        print(f"{i}sss{j}")


[[5 3 4]
 [6 7 2]
 [1 9 8]]
45
0sss0
[[6 7 8]
 [1 9 5]
 [3 4 2]]
45
0sss3
[[9 1 2]
 [3 4 8]
 [5 6 7]]
45
0sss6
[[8 5 9]
 [4 2 6]
 [7 1 3]]
45
3sss0
[[7 6 1]
 [8 5 3]
 [9 2 4]]
45
3sss3
[[4 2 3]
 [7 9 1]
 [8 5 6]]
45
3sss6
[[9 6 1]
 [2 8 7]
 [3 4 5]]
45
6sss0
[[5 3 7]
 [4 1 9]
 [2 8 6]]
45
6sss3
[[2 8 4]
 [6 3 5]
 [1 7 9]]
45
6sss6


In [7]:
# column:[age,math-marks,science-marks]
import numpy as np;
data = np.array([[18,85,78],
                 [19,92,88],
                 [17,76,95],
                 [18,65,70],
                 [20,90,85],
                ])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [8]:
# find the average of student
np.mean(data[:,0])

np.float64(18.4)

In [23]:
# extract math marks of all students.
data[:,1]

array([90, 97, 81, 70, 95])

In [10]:
# find the highest science mark;
np.max(data[:,2])

np.int64(95)

In [11]:
# get details of the student who scored more than 90 in math.
data[:,1]>90

array([False,  True, False, False, False])

In [12]:
# increase math marks of all students by 5

data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [13]:
# find how many students are younger than 19
len(data[data[:,0]<19])

3

In [14]:
# calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [15]:
# get data of students who scored at least 80 in both subjects.

data[(data[:,1]>=80) & (data[:,2]>=80)]



array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [16]:
data



array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [17]:
# replace all science marks <75 with 0;
data[:,2][data[:,2]<75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])

In [18]:
import numpy as np

# Your 9x9 array
arr = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

# 1. Print each row separately
print("=== ROWS ===")
for i in range(arr.shape[0]):
    print(f"Row {i+1}: {arr[i]}")

# 2. Print each column separately
print("\n=== COLUMNS ===")
for j in range(arr.shape[1]):
    print(f"Column {j+1}: {arr[:, j]}")

# 3. Print the full array
print("\n=== FULL ARRAY ===")
print(arr)

=== ROWS ===
Row 1: [5 3 4 6 7 8 9 1 2]
Row 2: [6 7 2 1 9 5 3 4 8]
Row 3: [1 9 8 3 4 2 5 6 7]
Row 4: [8 5 9 7 6 1 4 2 3]
Row 5: [4 2 6 8 5 3 7 9 1]
Row 6: [7 1 3 9 2 4 8 5 6]
Row 7: [9 6 1 5 3 7 2 8 4]
Row 8: [2 8 7 4 1 9 6 3 5]
Row 9: [3 4 5 2 8 6 1 7 9]

=== COLUMNS ===
Column 1: [5 6 1 8 4 7 9 2 3]
Column 2: [3 7 9 5 2 1 6 8 4]
Column 3: [4 2 8 9 6 3 1 7 5]
Column 4: [6 1 3 7 8 9 5 4 2]
Column 5: [7 9 4 6 5 2 3 1 8]
Column 6: [8 5 2 1 3 4 7 9 6]
Column 7: [9 3 5 4 7 8 2 6 1]
Column 8: [1 4 6 2 9 5 8 3 7]
Column 9: [2 8 7 3 1 6 4 5 9]

=== FULL ARRAY ===
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [19]:

for i in range(0,10,2):
    for j in range(0,9,3):
        print(i,j)

0 0
0 3
0 6
2 0
2 3
2 6
4 0
4 3
4 6
6 0
6 3
6 6
8 0
8 3
8 6
