In [2]:
import numpy as np;

In [3]:
# Numpy indexing and slicing of vectors
import numpy as np;
np.arange(11,21)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr =np.arange(11,21)
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
arr[1::2]


array([14, 18])

In [6]:
# NUMPY INDEXING AND SLICING OF MATRIX
arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [7]:
arr[3:6,3:5]


array([[19, 20],
       [24, 25],
       [29, 30]])

In [8]:
# Boolean indexing
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [10]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])